# Generated by Django 4.2 on 2023-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Название форума')),
                ('description', models.CharField(max_length=127, null=True, verbose_name='Описание форума')),
                ('chat_id', models.BigIntegerField(default=-1001900882163, verbose_name='Айди форума для отправки сообщения в него')),
            ],
            options={
                'verbose_name': 'Форум',
                'verbose_name_plural': 'Форумы',
            },
        ),
    ]
