# Generated by Django 4.2 on 2023-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='max_entry_tries',
            field=models.IntegerField(default=3),
        ),
    ]
