# Generated by Django 4.2 on 2023-04-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=127, null=True, verbose_name='Описание форума'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Название форума'),
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_send', models.BooleanField(default=True, verbose_name='Активность приветствия')),
                ('duration_in_sec', models.IntegerField(verbose_name='Продолжительность приветствия, сек')),
                ('to_delete_previous', models.BooleanField(default=False, verbose_name='Удалять предыдущее')),
                ('to_pin', models.BooleanField(default=False, verbose_name='Закреплять приветствие')),
                ('delay_in_sec', models.IntegerField(verbose_name='Задержка между отправками, сек')),
                ('text', models.CharField(max_length=127, verbose_name='Текст приветствия')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязано приветствие')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
        ),
        migrations.CreateModel(
            name='MathCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('text', models.CharField(max_length=31, verbose_name='Текст вопроса')),
                ('right_answer', models.CharField(max_length=31, verbose_name='Правильный ответ')),
                ('first_wrong_answer', models.CharField(max_length=31, verbose_name='Первый неправильный ответ')),
                ('second_wrong_answer', models.CharField(max_length=31, verbose_name='Второй неправильный ответ')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
        ),
    ]
