# Generated by Django 4.2 on 2023-04-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0003_forum_mute_time_sec_alter_forum_max_entry_tries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumblockeduser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='forumentrytry',
            name='id',
        ),
        migrations.AlterField(
            model_name='forumblockeduser',
            name='tg_user',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forumentrytry',
            name='tg_user',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
