# Generated by Django 4.2 on 2023-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0004_alter_mathcaptchasolver_tries_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttoncaptcha',
            name='first_wrong_answer',
        ),
        migrations.RemoveField(
            model_name='buttoncaptcha',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='buttoncaptcha',
            name='second_wrong_answer',
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='fifth_wrong_answer',
            field=models.CharField(default='5', max_length=31, verbose_name='Пятый неправильный ответ'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='first_wrong_answer',
            field=models.CharField(default='1', max_length=31, verbose_name='Первый неправильный ответ'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='fourth_wrong_answer',
            field=models.CharField(default='4', max_length=31, verbose_name='Четвертый неправильный ответ'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='right_answer',
            field=models.CharField(default='0', max_length=31, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='second_wrong_answer',
            field=models.CharField(default='2', max_length=31, verbose_name='Второй неправильный ответ'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='text',
            field=models.CharField(default=' ', max_length=31, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='third_wrong_answer',
            field=models.CharField(default='3', max_length=31, verbose_name='Третий неправильный ответ'),
        ),
        migrations.AlterField(
            model_name='buttoncaptcha',
            name='text',
            field=models.CharField(max_length=31, verbose_name='Текст кнопки'),
        ),
    ]
