# Generated by Django 4.2 on 2023-04-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0005_remove_buttoncaptcha_first_wrong_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttoncaptcha',
            options={'verbose_name': 'Кнопочная капча', 'verbose_name_plural': 'Кнопочные капчи'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name': 'Форум', 'verbose_name_plural': 'Форумы'},
        ),
        migrations.AlterModelOptions(
            name='mathcaptcha',
            options={'verbose_name': 'Математическая капча', 'verbose_name_plural': 'Математические капчи'},
        ),
        migrations.AlterModelOptions(
            name='quizcaptcha',
            options={'verbose_name': 'Капча-викторина', 'verbose_name_plural': 'Капчи-викторины'},
        ),
        migrations.AlterModelOptions(
            name='welcomemessage',
            options={'verbose_name': 'Приветственное сообщение', 'verbose_name_plural': 'Приветственные сообщения'},
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='link_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WelcomeMessageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=31)),
                ('welcome_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.welcomemessage')),
            ],
        ),
    ]
