# Generated by Django 4.2 on 2023-04-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0006_alter_buttoncaptcha_options_alter_forum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomemessagebutton',
            options={'verbose_name': 'Inline-кнопка к приветствию', 'verbose_name_plural': 'Inline-кнопки к приветствию'},
        ),
        migrations.AlterField(
            model_name='welcomemessagebutton',
            name='text',
            field=models.CharField(max_length=31, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='welcomemessagebutton',
            name='welcome_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.welcomemessage', verbose_name='Привязка к приветствию'),
        ),
    ]
