# Generated by Django 4.2 on 2023-04-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0007_alter_welcomemessagebutton_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcaptcha',
            name='tries',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quizcaptcha',
            name='tries',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mathcaptchasolver',
            name='tries_left',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='QuizCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('tries_left', models.IntegerField(null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.quizcaptcha')),
            ],
        ),
    ]
