# Generated by Django 4.2 on 2023-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0008_mathcaptcha_tries_quizcaptcha_tries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathcaptchasolver',
            name='tries_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizcaptchasolver',
            name='tries_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
