# Generated by Django 4.2 on 2023-04-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0009_alter_mathcaptchasolver_tries_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('set_time_expiration_tries', models.DateTimeField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.buttoncaptcha')),
            ],
        ),
    ]
