# Generated by Django 4.2 on 2023-04-18 17:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0011_rename_set_time_expiration_tries_buttoncaptchasolver_time_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomemessage',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
