# Generated by Django 4.2 on 2023-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0012_alter_welcomemessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='chat_id',
            field=models.BigIntegerField(default=-1001900882163, verbose_name='Айди форума для отправки сообщения в него'),
        ),
    ]
