# Generated by Django 4.2 on 2023-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0013_forum_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessagebutton',
            name='button_url',
            field=models.CharField(default=' ', max_length=127, verbose_name='Ссылка для инлайн кнопки'),
        ),
    ]
