# Generated by Django 4.2 on 2023-04-19 11:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('text', models.CharField(max_length=31, verbose_name='Текст кнопки')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Кнопочная капча',
                'verbose_name_plural': 'Кнопочные капчи',
            },
        ),
        migrations.CreateModel(
            name='MathCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('tries', models.IntegerField(default=5)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Математическая капча',
                'verbose_name_plural': 'Математические капчи',
            },
        ),
        migrations.CreateModel(
            name='QuizCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('text', models.CharField(max_length=31, verbose_name='Текст вопроса')),
                ('right_answer', models.CharField(max_length=31, verbose_name='Правильный ответ')),
                ('first_wrong_answer', models.CharField(max_length=31, verbose_name='Первый неправильный ответ')),
                ('second_wrong_answer', models.CharField(max_length=31, verbose_name='Второй неправильный ответ')),
                ('third_wrong_answer', models.CharField(max_length=31, verbose_name='Третий неправильный ответ')),
                ('fourth_wrong_answer', models.CharField(max_length=31, verbose_name='Четвертый неправильный ответ')),
                ('fifth_wrong_answer', models.CharField(max_length=31, verbose_name='Пятый неправильный ответ')),
                ('tries', models.IntegerField(default=1)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Капча-викторина',
                'verbose_name_plural': 'Капчи-викторины',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_send', models.BooleanField(default=True, verbose_name='Активность приветствия')),
                ('duration_in_sec', models.IntegerField(verbose_name='Продолжительность приветствия, сек')),
                ('to_delete_previous', models.BooleanField(default=False, verbose_name='Удалять предыдущее')),
                ('to_pin', models.BooleanField(default=False, verbose_name='Закреплять приветствие')),
                ('delay_in_sec', models.IntegerField(verbose_name='Задержка между отправками, сек')),
                ('text', ckeditor.fields.RichTextField()),
                ('link_preview', models.BooleanField(default=False)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязано приветствие')),
            ],
            options={
                'verbose_name': 'Приветственное сообщение',
                'verbose_name_plural': 'Приветственные сообщения',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=31, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(max_length=127, verbose_name='Ссылка для инлайн кнопки')),
                ('welcome_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.welcomemessage', verbose_name='Привязка к приветствию')),
            ],
            options={
                'verbose_name': 'Inline-кнопка к приветствию',
                'verbose_name_plural': 'Inline-кнопки к приветствию',
            },
        ),
        migrations.CreateModel(
            name='QuizCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('tries_left', models.IntegerField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.quizcaptcha')),
            ],
        ),
        migrations.CreateModel(
            name='MathCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('tries_left', models.IntegerField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.mathcaptcha')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.buttoncaptcha')),
            ],
        ),
    ]
