# Generated by Django 4.2 on 2023-04-22 14:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('text', models.CharField(max_length=31, verbose_name='Текст кнопки')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Кнопочная капча',
                'verbose_name_plural': 'Кнопочные капчи',
            },
        ),
        migrations.CreateModel(
            name='CaptchaMessageWasSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MathCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('tries', models.IntegerField(default=5, verbose_name='Попыток')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Математическая капча',
                'verbose_name_plural': 'Математические капчи',
            },
        ),
        migrations.CreateModel(
            name='QuizCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time_sec', models.IntegerField(verbose_name='Время активности капчи, сек')),
                ('text', models.CharField(max_length=31, verbose_name='Текст вопроса')),
                ('right_answer', models.CharField(max_length=31, verbose_name='Правильный ответ')),
                ('first_wrong_answer', models.CharField(max_length=31, verbose_name='Первый неправильный ответ')),
                ('second_wrong_answer', models.CharField(max_length=31, verbose_name='Второй неправильный ответ')),
                ('third_wrong_answer', models.CharField(max_length=31, verbose_name='Третий неправильный ответ')),
                ('fourth_wrong_answer', models.CharField(max_length=31, verbose_name='Четвертый неправильный ответ')),
                ('fifth_wrong_answer', models.CharField(max_length=31, verbose_name='Пятый неправильный ответ')),
                ('tries', models.IntegerField(default=1)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязана капча')),
            ],
            options={
                'verbose_name': 'Капча-викторина',
                'verbose_name_plural': 'Капчи-викторины',
            },
        ),
        migrations.CreateModel(
            name='SilentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Режим активен')),
                ('allow_admin', models.BooleanField(default=True, verbose_name='Админам можно писать')),
                ('start_text', ckeditor.fields.RichTextField(verbose_name='Сообщение в начале режима тишины')),
                ('end_text', ckeditor.fields.RichTextField(verbose_name='Сообщение в конце режима тишины')),
                ('start_time', models.TimeField(verbose_name='Время начала режима тишины')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания режима тишины. Оставить пустым,если указана продолжительность')),
                ('lasting_time_min', models.IntegerField(blank=True, null=True, verbose_name='Продолжительность режима тишины.Оставить пустым, если указано время окончания')),
                ('regularity', models.PositiveIntegerField(verbose_name='Повторять каждые ... дней.')),
            ],
            options={
                'verbose_name': 'Режим тишины',
                'verbose_name_plural': 'Режими тишины',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('tg_user', models.IntegerField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_send', models.BooleanField(default=True, verbose_name='Активность приветствия')),
                ('duration_in_sec', models.IntegerField(verbose_name='Продолжительность приветствия, сек')),
                ('to_delete_previous', models.BooleanField(default=False, verbose_name='Удалять предыдущее')),
                ('to_pin', models.BooleanField(default=False, verbose_name='Закреплять приветствие')),
                ('delay_in_sec', models.IntegerField(verbose_name='Задержка между отправками, сек')),
                ('text', ckeditor.fields.RichTextField()),
                ('link_preview', models.BooleanField(default=False)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum', verbose_name='Форум, к которому привязано приветствие')),
            ],
            options={
                'verbose_name': 'Приветственное сообщение',
                'verbose_name_plural': 'Приветственные сообщения',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessageWasSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=31, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(max_length=127, verbose_name='Ссылка для инлайн кнопки')),
                ('x', models.IntegerField(default=50)),
                ('y', models.IntegerField(default=50)),
                ('welcome_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.welcomemessage', verbose_name='Привязка к приветствию')),
            ],
            options={
                'verbose_name': 'Inline-кнопка к приветствию',
                'verbose_name_plural': 'Inline-кнопки к приветствию',
            },
        ),
        migrations.CreateModel(
            name='SilentModeWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_admin', models.BooleanField(blank=True, null=True)),
                ('silent_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.silentmode')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('tries_left', models.IntegerField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.quizcaptcha')),
            ],
        ),
        migrations.CreateModel(
            name='MathCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('tries_left', models.IntegerField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.mathcaptcha')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonCaptchaSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user', models.CharField(max_length=11)),
                ('time_expiration', models.DateTimeField(blank=True, null=True)),
                ('captcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_api.buttoncaptcha')),
            ],
        ),
    ]
