# Generated by Django 4.2 on 2023-04-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0001_initial'),
        ('welcome_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='silentmode',
            options={'verbose_name': 'Режим тишины', 'verbose_name_plural': 'Режимы тишины'},
        ),
        migrations.AddField(
            model_name='silentmode',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum'),
        ),
    ]
