# Generated by Django 4.2 on 2023-04-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_api', '0001_initial'),
        ('welcome_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeMessageWasSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_api.forum')),
            ],
        ),
    ]
