# Generated by Django 4.2 on 2023-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0002_welcomemessagewassent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomemessagewassent',
            name='forum',
        ),
        migrations.AddField(
            model_name='welcomemessagewassent',
            name='forum_chat_id',
            field=models.IntegerField(default=1),
        ),
    ]
