# Generated by Django 4.2 on 2023-04-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0003_remove_welcomemessagewassent_forum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathcaptcha',
            name='tries',
            field=models.IntegerField(default=5, verbose_name='Попыток'),
        ),
    ]
