# Generated by Django 4.2 on 2023-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0004_alter_mathcaptcha_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaMessageWasSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
            ],
        ),
    ]
