# Generated by Django 4.2 on 2023-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0005_captchamessagewassent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('tg_user', models.IntegerField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=511)),
            ],
        ),
    ]
