# Generated by Django 4.2 on 2023-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0006_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request',
            field=models.CharField(max_length=1023),
        ),
    ]
