# Generated by Django 4.2 on 2023-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_api', '0007_alter_userrequest_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessagebutton',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='welcomemessagebutton',
            name='y',
            field=models.IntegerField(default=50),
        ),
    ]
